name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 */5 * * *"

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        env:
          BEARER_TOKEN: ${{ secrets.JWT_TOKEN }}
        run: |
          timeout 5h npx cypress run

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: cypress/results

      - name: Archive screenshots and videos
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots-videos
          path: cypress/screenshots,cypress/videos