name: Cypress E2E Tests

on:
  push:
    branches:
      - main  # Run tests when code is pushed to the main branch
  pull_request:
    branches:
      - main  # Run tests on pull requests targeting the main branch

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use Node.js version 16 (or any version you need)

      # Step 3: Install dependencies
      - name: Install NPM dependencies
        run: npm install

      # Step 4: Run Cypress tests with an environment variable
      - name: Run Cypress tests
        run: npx cypress run
        env:
          CYPRESS_JWT_TOKEN: ${{ secrets.JWT_TOKEN }}  # Add this line to use the token


      # Optional: Upload test results as artifacts for inspection
      - name: Upload Cypress results
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: cypress/screenshots

      # Step 5: Cache Cypress binary
      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress
